#!/usr/bin/env python3.10
# =============================================================================
# c6.5_install_rival_stubs.py
#
# What this file does:
#   The comparison tests generated by codes/9b_synthesize_tests.py import their
#   "rival" baselines dynamically, e.g.:
#
#       __import__("assets.rivals.cot_baseline", fromlist=["run_eval"]).run_eval
#
#   They expect an importable Python package at
#   <repo>/assets/rivals/<slug>/__init__.py that exposes the named function.
#   The stage-6 downloader (codes/6_download_dataset.py) does NOT produce these
#   packages — it materializes datasets, cloned upstream repos, and manifests
#   under tests/harbor/.../assets/, with different slug names. As a result
#   scripts/run_tests_local.sh --reproduction aborts in preflight_rivals()
#   with "missing rival assets".
#
#   This script bridges that gap. It reads the comparison test files with the
#   `ast` module, discovers every `assets.rivals.<slug>` import and the
#   attribute each one needs, and writes a placeholder package per slug so the
#   imports resolve and the reproduction phase can run. By default each
#   placeholder raises NotImplementedError when called (an honest signal that
#   the rival baseline is not yet implemented). Iterations B/C/D of the plan
#   replace selected placeholders with real, paper-anchored implementations
#   marked with a "# PAPER-ANCHORED-MANUAL" header, which this script then
#   leaves untouched on subsequent runs.
#
# Usage example:
#   python3.10 codes/c6.5_install_rival_stubs.py \
#       --repo outputs/paperbench_repos/bbox_repo
#
#   # Overwrite even hand-edited rival modules:
#   python3.10 codes/c6.5_install_rival_stubs.py \
#       --repo outputs/paperbench_repos/bbox_repo --force
# =============================================================================

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

# Header marker placed on files this script generates. Files starting with this
# line are safe to regenerate; the user's own files are never clobbered.
AUTO_MARKER = "# AUTO-GENERATED-BY-c6.5_install_rival_stubs — safe to delete"

# Header marker for hand-written, paper-anchored rival implementations. Files
# starting with this line are preserved across runs (unless --force).
MANUAL_MARKER = "# PAPER-ANCHORED-MANUAL"


# Print an error message and exit nonzero so callers see a clear failure.
def die(message: str) -> "None":
    print(f"[install_rival_stubs] ERROR: {message}", file=sys.stderr)
    sys.exit(1)


# Parse one comparison test file and return {slug: set(attr_names)} for every
# __import__("assets.rivals.<slug>", fromlist=[...]) call found in it.
def discover_rivals_in_file(path: Path) -> "dict[str, set[str]]":
    found: "dict[str, set[str]]" = {}
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, SyntaxError) as exc:
        die(f"could not parse {path}: {exc}")

    # Walk every function call looking for the dynamic __import__ pattern.
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if not (isinstance(func, ast.Name) and func.id == "__import__"):
            continue
        if not node.args:
            continue
        module_arg = node.args[0]
        if not (isinstance(module_arg, ast.Constant) and isinstance(module_arg.value, str)):
            continue
        module_name = module_arg.value
        if not module_name.startswith("assets.rivals."):
            continue
        slug = module_name[len("assets.rivals."):]
        if not slug:
            continue

        # Collect the attribute names requested via fromlist=[...].
        attrs: "set[str]" = set()
        for kw in node.keywords:
            if kw.arg == "fromlist" and isinstance(kw.value, (ast.List, ast.Tuple)):
                for elt in kw.value.elts:
                    if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                        attrs.add(elt.value)
        found.setdefault(slug, set()).update(attrs)

    return found


# Scan all tests/comparison/*.py under the repo and merge their rival imports.
def discover_all_rivals(repo: Path) -> "dict[str, set[str]]":
    comp_dir = repo / "tests" / "comparison"
    if not comp_dir.is_dir():
        die(f"no comparison tests directory at {comp_dir}")

    merged: "dict[str, set[str]]" = {}
    for test_file in sorted(comp_dir.glob("*.py")):
        for slug, attrs in discover_rivals_in_file(test_file).items():
            merged.setdefault(slug, set()).update(attrs)
    return merged


# Load the stage-6 download summary (if present) and return the set of rival /
# metric slugs that were actually materialized. Used only to annotate the
# report as [backed] vs [unbacked]; never required.
def load_downloaded_names(harbor_summary: Path) -> "set[str]":
    if not harbor_summary.is_file():
        return set()
    import json

    try:
        data = json.loads(harbor_summary.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return set()

    names: "set[str]" = set()
    for item in data.get("items", []):
        if item.get("category") in ("rivals", "metrics"):
            name = item.get("name")
            if name:
                names.add(str(name))
    return names


# Heuristic: does any downloaded asset name plausibly back this test slug?
# Compares 4+ char tokens (split on "_") in both directions. Annotation only.
def is_backed(slug: str, downloaded: "set[str]") -> bool:
    slug_tokens = {t for t in slug.split("_") if len(t) >= 4}
    for name in downloaded:
        name_tokens = {t for t in name.split("_") if len(t) >= 4}
        if slug_tokens & name_tokens:
            return True
    return False


# Render the __init__.py body for one rival slug: an auto-marker header plus
# one NotImplementedError-raising stub per required attribute.
def render_stub_module(slug: str, attrs: "set[str]") -> str:
    lines = [
        AUTO_MARKER,
        f"# Rival baseline placeholder for assets.rivals.{slug}.",
        "# Required by tests/comparison/ (auto-discovered). Replace this file",
        "# with a real implementation (and a '# PAPER-ANCHORED-MANUAL' header)",
        "# to make the reproduction comparison meaningful.",
        "",
        "",
    ]
    # Emit a stub for each attribute the tests import (sorted for stable output).
    for attr in sorted(attrs) or ["__placeholder__"]:
        lines.append(f"def {attr}(*args, **kwargs):")
        lines.append(f'    """Stub for rival baseline {slug}.{attr} — not implemented."""')
        lines.append("    raise NotImplementedError(")
        lines.append(
            f'        "rival baseline assets.rivals.{slug}.{attr} is a stub installed by "'
        )
        lines.append('        "codes/c6.5_install_rival_stubs.py. Replace this file with a real "')
        lines.append('        "implementation before running the reproduction phase."')
        lines.append("    )")
        lines.append("")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# Decide whether an existing file may be overwritten, based on its header
# marker and the --force flag.
def may_overwrite(path: Path, force: bool) -> bool:
    if force or not path.exists():
        return True
    try:
        first_line = path.read_text(encoding="utf-8").splitlines()[0]
    except (OSError, IndexError):
        return True
    # Regenerate our own auto-stubs; preserve manual and unknown files.
    return first_line.startswith(AUTO_MARKER)


# Ensure an empty package marker exists so "assets" / "assets.rivals" import.
# Never overwrites a non-empty existing file.
def ensure_namespace_init(path: Path) -> None:
    if path.exists() and path.read_text(encoding="utf-8").strip():
        return
    path.write_text(
        AUTO_MARKER + "\n# Namespace package marker for rival baseline imports.\n",
        encoding="utf-8",
    )


# Orchestrate: discover rivals, write/refresh modules, print a report.
def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install importable rival-baseline placeholder packages so "
        "the reproduction comparison tests can be collected and run."
    )
    parser.add_argument(
        "--repo",
        required=True,
        help="Path to a paperbench repo (e.g. outputs/paperbench_repos/bbox_repo)",
    )
    parser.add_argument(
        "--harbor-summary",
        default="",
        help="Optional path to c1_download_dataset_summary.json (for [backed] "
        "annotation). Auto-resolved from the repo name when omitted.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite even manual/unknown rival modules.",
    )
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    if not repo.is_dir():
        die(f"repo directory not found: {repo}")

    rivals = discover_all_rivals(repo)
    if not rivals:
        print(
            "[install_rival_stubs] no assets.rivals.* imports found in "
            f"{repo / 'tests' / 'comparison'} — nothing to do."
        )
        return

    # Resolve the harbor download summary for [backed]/[unbacked] annotation.
    if args.harbor_summary:
        harbor_summary = Path(args.harbor_summary)
    else:
        paper = repo.name[:-len("_repo")] if repo.name.endswith("_repo") else repo.name
        # repo is <root>/outputs/paperbench_repos/<paper>_repo, so the project
        # root (which holds tests/harbor/) is three levels up.
        project_root = repo.parents[2]
        harbor_summary = (
            project_root
            / "tests"
            / "harbor"
            / "yantingchi"
            / paper
            / "harbor"
            / "asset"
            / "c1_download_dataset_summary.json"
        )
    downloaded = load_downloaded_names(harbor_summary)

    # Create the package namespace files.
    rivals_root = repo / "assets" / "rivals"
    rivals_root.mkdir(parents=True, exist_ok=True)
    ensure_namespace_init(repo / "assets" / "__init__.py")
    ensure_namespace_init(rivals_root / "__init__.py")

    print(f"[install_rival_stubs] repo:    {repo}")
    if downloaded:
        print(f"[install_rival_stubs] summary: {harbor_summary} ({len(downloaded)} downloaded)")
    else:
        print("[install_rival_stubs] summary: (none found — annotation skipped)")
    print(f"[install_rival_stubs] discovered {len(rivals)} required slug(s) from tests/comparison/.")

    wrote, kept = 0, 0
    for slug in sorted(rivals):
        attrs = rivals[slug]
        slug_dir = rivals_root / slug
        slug_dir.mkdir(parents=True, exist_ok=True)
        init_path = slug_dir / "__init__.py"
        backing = "backed" if is_backed(slug, downloaded) else "unbacked"
        attr_list = ", ".join(sorted(attrs)) or "(none)"

        if may_overwrite(init_path, args.force):
            init_path.write_text(render_stub_module(slug, attrs), encoding="utf-8")
            wrote += 1
            verb = "stub"
        else:
            kept += 1
            verb = "kept (manual)"
        print(f"[install_rival_stubs]   {slug:<32} → {verb} ({attr_list})  [{backing}]")

    print(
        f"[install_rival_stubs] wrote {wrote} module(s), kept {kept} existing "
        f"under {rivals_root}."
    )


if __name__ == "__main__":
    main()
