"""
datalog_solver.py

This module implements the DatalogSolver class for the TyPro pipeline.
It accepts an optimized list of Fact objects (from AST extraction and fact optimization),
converts them into CSV files (one per relation) expected by the Soufflé Datalog solver,
executes the solver using the provided Datalog rules (rules.dl),
and then parses its output to compute the TargetSet mapping, which maps each indirect call
identifier (callLabel) to a list of allowed function identifiers for that call.

The class adheres to the design specification and uses configuration settings
from 'config.yaml'. All temporary files and directories are created with default values
and are cleaned up after execution.
"""

import os
import subprocess
import tempfile
import shutil
import logging
from typing import List, Dict

# Import shared utilities and Fact class from utils.py.
from utils import Fact, parse_config, get_logger

class DatalogSolver:
    """
    DatalogSolver bridges the fact-based analysis and enforcement by invoking the Soufflé Datalog solver.

    Attributes:
        rules_file (str): Path to the Soufflé rules file (default "rules.dl").
        souffle_path (str): Path to the Soufflé binary (default "souffle").
        config (Dict[str, any]): Configuration loaded from config.yaml.
        logger (logging.Logger): Logger instance.
    """

    def __init__(self, rules_file: str = "rules.dl", souffle_path: str = "souffle") -> None:
        """
        Initialize a DatalogSolver instance with the specified rules file and Soufflé binary path.
        
        Args:
            rules_file (str): Path to the Datalog rules file. Default is "rules.dl".
            souffle_path (str): Path to the Soufflé binary. Default is "souffle".
        """
        self.config: Dict[str, any] = parse_config("config.yaml")
        self.rules_file: str = rules_file
        self.souffle_path: str = souffle_path
        self.logger: logging.Logger = get_logger("DatalogSolver")
        self.logger.debug("DatalogSolver initialized with rules_file='%s' and souffle_path='%s'.",
                          self.rules_file, self.souffle_path)

    def solve(self, facts: List[Fact]) -> Dict[str, List[int]]:
        """
        Solve the Datalog analysis to compute the TargetSet mapping.

        The method performs the following steps:
          1. Groups the given Fact objects by fact_type and writes each group to a CSV file in a temporary facts directory.
          2. Invokes the Soufflé Datalog solver with the provided rules file, specifying the input facts directory and an output directory.
          3. Parses the output "TargetSet.csv" file generated by Soufflé to build a mapping where each indirect call (callLabel)
             is mapped to a list of allowed function identifiers (as integers).
          4. Cleans up the temporary directories before returning the mapping.

        Args:
            facts (List[Fact]): Optimized list of Fact objects.

        Returns:
            Dict[str, List[int]]: A dictionary mapping each indirect call identifier to a list of allowed function IDs.

        Raises:
            RuntimeError: If the Soufflé solver fails or if the required output file is missing.
        """
        # Create temporary directories for the facts input and solver output.
        facts_dir: str = tempfile.mkdtemp(prefix="souffle_facts_")
        output_dir: str = tempfile.mkdtemp(prefix="souffle_output_")
        self.logger.info("Created temporary facts directory: %s", facts_dir)
        self.logger.info("Created temporary output directory: %s", output_dir)

        try:
            # Step 1: Group facts by fact_type.
            grouped_facts: Dict[str, List[Fact]] = {}
            for fact in facts:
                grouped_facts.setdefault(fact.fact_type, []).append(fact)
            self.logger.info("Grouped facts by relation: %s", list(grouped_facts.keys()))

            # Write each group of facts to a corresponding CSV file.
            for fact_type, fact_list in grouped_facts.items():
                file_path: str = os.path.join(facts_dir, f"{fact_type}.csv")
                with open(file_path, "w", encoding="utf-8") as csv_file:
                    for fact in fact_list:
                        csv_line: str = self._format_fact_as_csv(fact)
                        csv_file.write(csv_line + "\n")
                self.logger.debug("Wrote %d facts to file '%s'.", len(fact_list), file_path)

            # Step 2: Invoke Soufflé via subprocess.
            # Command structure: souffle -F <facts_dir> -D <output_dir> <rules_file>
            cmd: List[str] = [self.souffle_path, "-F", facts_dir, "-D", output_dir, self.rules_file]
            self.logger.info("Invoking Soufflé with command: %s", " ".join(cmd))
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode != 0:
                self.logger.error("Soufflé Datalog solver failed with exit code: %d", result.returncode)
                self.logger.error("Soufflé stderr: %s", result.stderr)
                raise RuntimeError("Soufflé Datalog solver execution failed.")
            self.logger.info("Soufflé Datalog solver completed successfully.")

            # Step 3: Parse the output file "TargetSet.csv".
            target_set_file: str = os.path.join(output_dir, "TargetSet.csv")
            if not os.path.exists(target_set_file):
                self.logger.error("Expected output file '%s' not found.", target_set_file)
                raise RuntimeError("Soufflé output missing TargetSet.csv file.")
            target_mapping: Dict[str, List[int]] = {}
            with open(target_set_file, "r", encoding="utf-8") as ts_file:
                for line in ts_file:
                    line = line.strip()
                    if not line:
                        continue
                    # Split the line by comma (CSV format, no header).
                    parts = line.split(",")
                    if len(parts) < 2:
                        self.logger.warning("Malformed line in TargetSet.csv: '%s'", line)
                        continue
                    call_id: str = parts[0].strip()
                    target_id_str: str = parts[1].strip()
                    try:
                        target_id: int = int(target_id_str)
                    except ValueError:
                        self.logger.warning("Non-integer function identifier '%s' in line: '%s'", target_id_str, line)
                        continue
                    if call_id not in target_mapping:
                        target_mapping[call_id] = []
                    target_mapping[call_id].append(target_id)
            self.logger.info("Parsed TargetSet mapping: %s", target_mapping)

            # Step 4: Return the computed mapping.
            return target_mapping

        finally:
            # Clean up temporary directories.
            try:
                shutil.rmtree(facts_dir)
                shutil.rmtree(output_dir)
                self.logger.debug("Cleaned up temporary directories.")
            except Exception as cleanup_error:
                self.logger.warning("Error during cleanup of temporary directories: %s", cleanup_error)

    def _format_fact_as_csv(self, fact: Fact) -> str:
        """
        Convert a Fact object into a CSV string suitable for Soufflé input.
        
        The CSV fields are ordered based on the fact_type as defined in the expected_fields mapping.
        If the fact_type is not recognized, the keys from fact.data are sorted alphabetically.

        Args:
            fact (Fact): The Fact object to format.
        
        Returns:
            str: A CSV-formatted string representing the fact.
        """
        expected_fields: Dict[str, List[str]] = {
            "TypeContextPair": ["id", "type", "context"],
            "PointsTo": ["ptr", "pointee"],
            "StructMember": ["parent", "member", "offset"],
            "UnionMember": ["parent", "member", "fieldType"],
            "Cast": ["src", "dst"],
            "ICall": ["callType", "callLabel", "arity"],
            "FunctionPointer": ["id", "func", "arity", "vararg"],
            "TypeCall": ["id", "type", "callLabel"]
        }
        field_order: List[str] = expected_fields.get(fact.fact_type)
        if field_order is None:
            field_order = sorted(fact.data.keys())
        values: List[str] = []
        for field in field_order:
            if field == "id" and fact.fact_type in {"TypeContextPair", "FunctionPointer", "TypeCall"}:
                value = fact.id
            else:
                value = fact.data.get(field)
            # Convert booleans to "true"/"false"
            if isinstance(value, bool):
                value_str = "true" if value else "false"
            elif isinstance(value, int):
                value_str = str(value)
            elif value is None:
                value_str = ""
            else:
                # Replace any commas in strings to avoid CSV conflicts.
                value_str = str(value).replace(",", ";")
            values.append(value_str)
        # Join the field values with commas.
        csv_line: str = ",".join(values)
        return csv_line
